# Generated by Django 5.2 on 2025-05-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootlocation',
            name='lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bootlocation',
            name='long',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favoritelocations',
            name='lat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favoritelocations',
            name='long',
            field=models.CharField(max_length=255),
        ),
    ]
