# Generated by Django 5.2 on 2025-05-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
            ],
        ),
    ]
